### ISSUE TITLE
Not working with Ryzen 3XXX

### ISSUE THREAD

**Issue by anat** [asadityas67/RyzenCodeDecoder#1]
Have you any idea how to decode it ? Didn't find anything on reddit :
http://www.moepc.net/content/uploadfile/201811/8d7b1542898939.png
http://www.moepc.net/content/uploadfile/201901/7a821548334088.png

If it is implementable it could be great =)

**Comment by asadityas67** [comment]
Dropping this project, as AMD has moved on from using these naming conventions.
they use numbers and it's not yet found how to decode them anymore.
